#This is the makefile to compile CSC777 Simulation and Calculation programs

simulate:
	gcc pascal_simulate.cpp -pthread -lstdc++ -std=c++0x -o pascal_simulate
calculate:
	gcc pascal_calc.cpp -lgmp -lstdc++ -o pascal_calc
clean:
	rm -f pascal_simulate pascal_calculate

